name: "Uniplus AWS Deploy"

on:
  push:
    branches: [ "main" ]

env:
  TF_VERSION: 1.10.5
  TF_LINT_VERSION: v0.52.0
  DESTROY: false
  ENVIRONMENT: production

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS | Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform-docs | Generate documentation
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: ./infra
          output-file: README.md
          output-method: inject
          git-push: "true"

      - name: Terraform | Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform | Initialize backend
        run: terraform init

      - name: Terraform | Format code
        run: terraform fmt

      - name: Terraform | Check Syntax IaC Code
        run: terraform validate

      # ... (TFlint e TFSec omitidos para brevidade, mantenha-os como estão no seu arquivo)

      - name: Terraform | Plan
        run: terraform plan -out tfplan.binary
        env:
          # Injeção das variáveis do RDS via Secrets
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      - name: Terraform | Show to json file
        run: terraform show -json tfplan.binary > plan.json

      - name: Terraform | Apply
        if: env.DESTROY == 'false'
        run: terraform apply -auto-approve tfplan.binary
        env:
          # Repetir aqui para garantir que o Apply tenha acesso às credenciais
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      - name: Terraform Destroy
        if: env.DESTROY == 'true'
        run: terraform destroy -auto-approve
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}